language: csharp
sudo: required
solution: Snowflake.sln
mono: none
dotnet: 2.1.2
dist: trusty 
osx_image: xcode8.3
os:
  - linux
  - osx
matrix:
  fast_finish: true
  allow_failures:
    - os: osx
  
script:
  - ./build/build.sh --script "./build/build.cake" -target=Travis
