version: 0.2.{build}
os: Visual Studio 2017
branches:
  # whitelist
  only:
    - master
skip_tags: true
clone_depth: 50
test:
  assemblies:
    - Snowflake.Framework.Tests.dll
configuration: Debug
# Fix line endings on Windows
init:
  - git config --global core.autocrlf true

environment:
    COVERALLS_REPO_TOKEN:
      secure: nBi3LwnqgslaH8hbsvjnWTqpe/UbKn705TJujxqJwtcL5OLGfcydM8AnVyld6Ngu
    CoverityProjectToken:
      secure: 5cuY6qLcjz85TBpjs2Ba9B8QKKT5XuvQse3pnVmk8wo=
    CoverityNotificationEmail:
      secure: YObG6alHbjgc0M1b5aIThLfeiTS18PFiFnIjEcSNqa0=
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
    GITHUB_BUILDBOT_TOKEN:
      secure: LZO5KXv/W++ny6vI/qhQ/NhscaTqhFAe+h3t0/sTMj44LlGeJi3n7nIR9b8KXXHr
cache:
  - packages -> **\packages.config
  
install:
    - nuget update -self > nul 2>&1
    - git submodule update --init --recursive > nul 2>&1
    - rem USING DOTNET SDK VERSION
    - dotnet --version

build_script:
    - ps: .\build\build.ps1 -Script build\build.cake -Target Appveyor

artifacts:
    - path: 'build\out\Snowflake.Framework.Primitives.*.nupkg'
      name: Snowflake Framework Primitives Interfaces
      type: NuGetPackage
      
    - path: 'build\out\Snowflake.Framework.*.nupkg'
      name: Snowflake Framework Base Classes
      type: NuGetPackage
      
    - path: 'build\out\Snowflake.Framework.Services.*.nupkg'
      name: Snowflake Framework Service Classes
      type: NuGetPackage
      
    - path: 'build\out\Snowflake.Framework.Persistence.*.nupkg'
      name: Snowflake Framework Persistence Base Classes
      type: NuGetPackage
      
    - path: 'build\out\Snowflake.Framework.Remoting.GraphQl.*.nupkg'
      name: Snowflake Framework GraphQL Remoting Base Classes
      type: NuGetPackage
      
    - path: 'build\out\*.snowpkg'
      name: 'Snowflake Support Package'
      type: File

deploy:
    - provider: NuGet
      server: https://www.myget.org/F/snowflake-nightly/api/v2/package
      api_key:
        secure: c0TSni4oM3D75P31isNFRu0z4whPsrvTAcu67iLlFmtvvrzopEI8Xj5qWk1pwMkj
      symbol_server: https://nuget.symbolsource.org/MyGet/snowflake-nightly
      skip_symbols: false
after_deploy:
    - rem Uploading Build Documentation
    - git init doc/html
on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
#    - echo docs.snowflakepowe.red > doc/html/CNAME
 #   - echo > doc/html/.nojekyll
 #   - git -C doc/html add --all > nul 2>&1
 #   - git -C doc/html commit -m "Upload documentation for build SnowflakePowered/snowflake@%APPVEYOR_REPO_COMMIT%" > nul 2>&1
 #   - git -C doc/html push --force -q https://snowflake-build-bot:%GITHUB_BUILDBOT_TOKEN%@github.com/SnowflakePowered-Support/snowflake-doc-doxygen.git master  
