codecov:
  branch: master       # the branch to show by default, inherited from your git repository settings
  strict_yaml_branch: master
github_checks:
  annotations: true
coverage:
  precision: 2
  round: down
  range: "70...90"
  fixes:
    - "build/::"
  status:
    project:
      default:
        target: auto
        if_no_uploads: error
        threshold: 2%
    patch:
      default:
        if_no_uploads: error
        target: 50%
        threshold: 10%

comment:
  layout: "header, diff, changes, suggestions, sunburst"
  behavior: default

codecov:
  token: 82f2a4f6-6167-45f5-bc8b-8b10f601dab4